"""empty message

Revision ID: 508d7669521f
Revises: 9a216fa5b1f4
Create Date: 2016-05-15 17:46:43.419174

"""

# revision identifiers, used by Alembic.
revision = '508d7669521f'
down_revision = '9a216fa5b1f4'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('keyword_relevance')
    op.drop_table('image')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', sa.INTEGER(), server_default=sa.text(u"nextval('image_id_seq'::regclass)"), nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'image_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('keyword_relevance',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('keyword', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('relevance', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], [u'image.id'], name=u'keyword_relevance_parent_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'keyword_relevance_pkey')
    )
    ### end Alembic commands ###
